---
- hosts: 127.0.0.1
  connection: local
  gather_facts: true
  vars:
    gvm_root: "{{ ansible_env.HOME }}/.gvm"
    rvm_root: "{{ ansible_env.HOME }}/.rvm"
  pre_tasks:
    - name: Check if GVM exists
      stat: path="{{ gvm_root }}"
      register: gvm_exists
    - name: Check if RVM exists
      stat: path="{{ rvm_root }}"
      register: rvm_exists    
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      tags: [ 'packages' ]
    - name: Install basic packages
      apt: name={{item}} state=present
      with_items:
        - git
        - wget
      become: true
      tags: [ 'packages' ] 
  roles:
  # Missing the KeePassX role
    - role: mhalano.skypeforlinux
      become: true
    - role: altermn.rvm
      rvm_install_type: user
      when: rvm_exists.stat.exists == false
    - role: suzuki-shunsuke.gvm
      gvm_rc_path: "{{ ansible_env.HOME }}/.bashrc"
      when: gvm_exists.stat.exists == false
    - role: azavea.terraform
      terraform_version: 0.9.9
      become: true
    - role: gantsign.visual-studio-code
      become: true
    - role: henriklynggaard.keepassxc
      become: true
  tasks:
    - name: Install software packages
      apt: name={{item}} state=present
      with_items:
        - dropbox
        - virtualbox-qt
        - vagrant
        - vim
        - tmux
        - neovim
        - xsel
      become: true
      tags: [ 'packages' ]
    - name: Get the N7 Wallpaper
      get_url:
        url: http://cdn.wallpapersafari.com/72/4/O937pm.png
        dest: /tmp/n7-wp.png
        mode: 0440
    - name: Install the Wallpaper
      command: "gsettings set org.gnome.desktop.background picture-uri file:////tmp/n7-wp.png"

      
