---
- hosts: localhost
  gather_facts: false
  vars:
    http_port: 80
    max_clients: 200
#  remote_user: root
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      tags: [ 'packages' ]
    - name: Install basic packages
      apt: name={{item}} state=present
      with_items:
        - git
      tags: [ 'packages' ]